name: go-test
on:
  push:
    tags:
      - v*
    branches-ignore:
      - 'doc-*'
      - 'doc/*'
  pull_request:
    branches:
      - main
      - master
      - release
jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - uses: actions/checkout@v3
      - name: go-test
        run: |
          go test -v -count=1 \
                  -covermode=count \
                  -coverpkg=github.com/tunabay/go-filecache \
                  -coverprofile=cover.out \
                  ./...
          go tool cover -func=cover.out
          go tool cover -html=cover.out -o go-test-coverage.html
      - uses: actions/upload-artifact@v3
        with:
          path: go-test-coverage.html
          retention-days: 3
